[package]
name = "jetson-watchdog"
version = "0.1.0"
authors = ["heistcc1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logwatcher = "0.1"
difference = "2.0"
daemonize =  "0.4.1"
regex = "1.3.7"
